formatter: markdown table
version: ">= 0.17"

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true
  description: true
  hide-empty: true
  type: true
  required: true
  sensitive: true
