name: ci

on:
  pull_request:
  push:
    branches: [master]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - run: terraform fmt -check -recursive

  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - azure/aks
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - name: init
        working-directory: ${{ matrix.module }}
        run: terraform init -backend=false
      - name: validate
        working-directory: ${{ matrix.module }}
        run: terraform validate
